### ISSUE TITLE
If a bookshelf model does not have timestamps an error is thrown

### ISSUE THREAD

**Issue by alarner** [alarner/bookshelf-api#5]
```html
<h1>model.hasTimestamps.indexOf is not a function</h1>
<h2></h2>
<pre>TypeError: model.hasTimestamps.indexOf is not a function
   at module.exports (/Users/admin/tiy/final-project/node_modules/bookshelf-api/dist/get.js:7:26)
   at /Users/admin/tiy/final-project/node_modules/bookshelf-api/dist/middleware.js:46:11
   at Layer.handle [as handle_request] (/Users/admin/tiy/final-project/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:312:13)
   at /Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:271:10)
   at module.exports (/Users/admin/tiy/final-project/lib/middleware/logged-in.js:8:3)
   at Layer.handle [as handle_request] (/Users/admin/tiy/final-project/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:312:13)
   at /Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:271:10)
   at Function.handle (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:176:3)
   at router (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:46:12)
   at Layer.handle [as handle_request] (/Users/admin/tiy/final-project/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:312:13)
   at /Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/admin/tiy/final-project/node_modules/express/lib/router/index.js:271:10)
   at SessionStrategy.strategy.pass (/Users/admin/tiy/final-project/node_modules/passport/lib/middleware/authenticate.js:325:9)
   at /Users/admin/tiy/final-project/node_modules/passport/lib/strategies/session.js:65:12</pre>
```

**Comment by jpchip** [comment]
Hey @alarner, was playing around with your library and ran across this same bug. It looks like this fix hasn't made it into the dist yet. Can you build and cut a new version with this fix?

**Comment by alarner** [comment]
Thanks for the heads up @jpchip. Just pushed a new version with that fix included https://github.com/alarner/bookshelf-api/blob/v1.7.1/dist/get.js#L10

Let me know if it's still not working.
